### ISSUE TITLE
Unable to configure if you disable notifications.

### ISSUE THREAD

**Issue by mercianary** [pelya/screen-dimmer-pixel-filter#1]
The first thing I did was disable notifications to get rid of the persistent notification (I know, its necessary).  But after doing so you are unable to configure the app as when you launch it either turns it on or off.  The only way to configure is to press the notification...if the user chooses to hide the notification there is no way to configure after the first run.

If the pixel filter is on and you open pixel filter app, it should go to the configuration screen, not turn it off.

**Comment by pelya** [comment]
I've copied this behavior from the Screen Filter app. I guess I'll just add
an option to disable notification to the Pixel Filter itself, and then show
config as you describe.

**Comment by pelya** [comment]
Fixed.
