### ISSUE TITLE
Quick Settings Tile

### ISSUE THREAD

**Issue by PrototypeNM1** [pelya/screen-dimmer-pixel-filter#10]
The current UI in the Notification Drawer can shift around due to competing notifications, especially first thing in the morning if the app wasn't disabled the night before. This is an issue as notification can be difficult to spot with the dimmed screen.

Having a Quick Settings Tile is more consistent with similar hardware controls (Wifi/BT, flashlight, screen brightness), and would be a more static location can can be found via muscle memory. It would also allow for a more consistent UX with other hardware controls: toggle on/off from the Notification Drawer view of Quick Settings, open Pixel Filter settings from the full Quick Settings view.

**Comment by pelya** [comment]
https://github.com/pelya/screen-dimmer-pixel-filter/pull/13
